apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailing-deployment
  labels:
    app: emailing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailing
  template:
    metadata:
      labels:
        app: emailing
    spec:
      containers:
        - name: emailing
          image: markoambrozic/emailing:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: dbuser
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: postgres
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379